### ISSUE TITLE
bug with identify_anchor_kmer_in_reference_graph (patient_graph.py) function

### ISSUE THREAD

**Issue by JRudewicz** [cbib/MICADo#16]
Traceback (most recent call last):
  File "src/principal.py", line 280, in <module>
    disable_cycle_breaking=args.disable_cycle_breaking
  File "src/principal.py", line 109, in process_sample
    g_patient.alteration_list_init(g_reference.dbg, kmer_length, min_support_percentage, max_len)
  File "/home/jrudewicz/MICADo/src/patient_graph.py", line 182, in alteration_list_init
    path_length=len(alternative_path))
  File "/home/jrudewicz/MICADo/src/patient_graph.py", line 50, in identify_anchor_kmer_in_reference_graph
    idx = toposort[rightmost]
KeyError: 'ACAGGCGACTTTCAGCAGAG'

**Comment by JRudewicz** [comment]
no more error.
