### ISSUE TITLE
AttributeError: 'OutDegreeView' object has no attribute 'items'

### ISSUE THREAD

**Issue by mcortes-lopez** [cbib/MICADo#23]
I was running the example data set and I got this error:

Traceback (most recent call last):
```
  File "src/MICADo.py", line 186, in <module>
    disable_cycle_breaking=args.disable_cycle_breaking
  File "src/MICADo.py", line 71, in process_sample
    g_patient.alteration_list_init(g_reference.dbg, kmer_length, min_support_percentage, max_len)
  File "/my/path/MICADo/src/patient_graph.py", line 150, in alteration_list_init
    end_tips_list = [key for key, v in self.dbgclean.out_degree().items() if
AttributeError: 'OutDegreeView' object has no attribute 'items'

```

**Comment by JRudewicz** [comment]
Hi,
Which version of python and networkx are you using?

**Comment by mcortes-lopez** [comment]
Python 2.7.14 and Networkx  2.2

**Comment by JRudewicz** [comment]
Versions are ok. 
Could you send me the command line you run please?
